<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ScannerGUIv3.Core</RootNamespace>
    <Platforms>x64</Platforms>
    <Platforms>x64</Platforms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Contracts\Services\ISampleDataService.cs" />
    <Compile Remove="Models\SampleCompany.cs" />
    <Compile Remove="Models\SampleOrder.cs" />
    <Compile Remove="Models\SampleOrderDetail.cs" />
    <Compile Remove="Services\SampleDataService.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Contracts\Services\ISampleDataService.cs" />
    <None Include="Models\SampleCompany.cs" />
    <None Include="Models\SampleOrder.cs" />
    <None Include="Models\SampleOrderDetail.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>
</Project>
