<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ScannerGUIv3.Core</RootNamespace>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <Platforms>x86;x64;arm64;AnyCPU</Platforms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Contracts\Services\ISampleDataService.cs" />
    <Compile Remove="Models\SampleCompany.cs" />
    <Compile Remove="Models\SampleOrder.cs" />
    <Compile Remove="Models\SampleOrderDetail.cs" />
    <Compile Remove="Services\SampleDataService.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Contracts\Services\ISampleDataService.cs" />
    <None Include="Models\SampleCompany.cs" />
    <None Include="Models\SampleOrder.cs" />
    <None Include="Models\SampleOrderDetail.cs" />
    <None Include="Services\SampleDataService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.13.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
